### ISSUE TITLE
Is it usable in a objective-c project?

### ISSUE THREAD

**Issue by appfabtech** [szk-atmosphere/SAHistoryNavigationViewController#10]
Thanks

**Comment by marty-suzuki** [comment]
Hi, @pcecchetti!
Thanks for your question.

You can use SAHistoryNavigationViewController in objective-c project.

#### How to use

You have to add [SAHistoryNavigationViewController directory](https://github.com/szk-atmosphere/SAHistoryNavigationViewController/tree/master/SAHistoryNavigationViewController) in your objective-c project.

`<# ProductName #>-Swift.h` is automatically generated in you project, so you import `<# ProductName #>-Swift.h` in *.h or *.m file where you want to use SAHistoryNavigationViewController. (If you can not import `<# ProductName #>-Swift.h`, please try once to build your project without import it.  Then you might be able to import.) 

#### This is sample code for Objective-C

``` objective-c
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
ViewController *viewControlelr = [storyboard instantiateViewControllerWithIdentifier:@"ViewController"];

SAHistoryNavigationViewController *navigationController = [[SAHistoryNavigationViewController alloc] initWithRootViewController:viewControlelr];
[self presentViewController:navigationController animated:true completion:nil];
```

In addiotion, this is link for Apple Official Document of [Using Swift from Objective-C](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-XID_87).

Thank you.

**Comment by pepejeria** [comment]
I manually added the SAHistoryNavigationViewController directory to my Objective-C project (I also have a <project-name>-Bridging-Header.h file), but I am getting a "Unknown class SAHistoryNavigationViewController in Interface Builder file." error. Do you know what could be the cause of this problem?

**Comment by marty-suzuki** [comment]
You need to import "[Your Project Name]-Swift.h" in you objective-c files.

bridge-header.h is used to import objective-c class from swift class.
xxx-Swift.h is used to import swift class from objective-c class.
