### ISSUE TITLE
Any way to disable the custom navigation animation?

### ISSUE THREAD

**Issue by ayushgoel** [szk-atmosphere/SAHistoryNavigationViewController#15]

**Comment by marty-suzuki** [comment]
There are no way to disable the custom navigation animation, now.
I'll improve that feature.

**Comment by marty-suzuki** [comment]
thanks for your pull request!
i've merged.
but it is not enough to work normally for edge-swiping.
i'll fix it.

**Comment by marty-suzuki** [comment]
i've fixed!
you can use default animation on [1.2.2](https://github.com/szk-atmosphere/SAHistoryNavigationViewController/tree/1.2.2).
i'll push new version to cocoapods

**Comment by ayushgoel** [comment]
We can close this issue once the new version is published. Thanks! :+1:

**Comment by marty-suzuki** [comment]
1.2.2 has been published on cocoapods!
Thanks!
