### ISSUE TITLE
Crash when navigation between screens is half complete and reverted

### ISSUE THREAD

**Issue by giridharvc7** [szk-atmosphere/SAHistoryNavigationViewController#8]
Hi, 
First off, great control utility for ios, thanks a bunch, 
I came across this peculiar bug, i've uploaded the procedure here, and its reproducible.
Please have a look. I'm trying to fix this up myself, i'll submit a pull request if i'm successful :)
https://www.youtube.com/watch?v=unzY6lAhSeo&feature=youtu.be

**Comment by marty-suzuki** [comment]
Hi, thanks for reporting bug.
I've fixed it and released as ver 1.1.1 at CocoaPods.
Please check it out!

**Comment by giridharvc7** [comment]
I think the edgeswiping case has come again now after your latest commit. I have a Side menu, and i swipe left to open the menu, the app crashes because of the edge swipe.

**Comment by marty-suzuki** [comment]
Thanks for reporting a bug.
I have to write code that avoiding edge swipe for navigation transition when navigation stack is one.
This is a cause for this case.
Sorry for forgetting to write single stack case code.
I'll fix it in 24 hours!

**Comment by giridharvc7** [comment]
Please, you don't have to be sorry, everyone makes mistakes :)
I think i've fixed the issue, i've created a pull request, please have a look

**Comment by marty-suzuki** [comment]
Thanks for your pull request.
I've released version 1.2.1 on cocoapods.
Please try it.
Thank you!!
